### ISSUE TITLE
Got Permission denied from pipecd-gateway.

### ISSUE THREAD

**Issue by k-ngs** [pipe-cd/tutorial#14]
First of all, I appriciate your efforts!

## Bug Description
In `Install Control Plane`, when I execute `docker-compose up` , pipecd-gateway did not start and I could not access the console.

I got the following logs from pipecd-gateway

```
[pipecd-gateway] | chown: /dev/stdout: Permission denied
[pipecd-gateway] | chown: /dev/stderr: Permission denied
```

My local environment is below.
* Macbook Pro 2020 M1
* macOS Sonoma v14.2.1
* Podman v5.2.0
* podman-compose v1.2.0

## Workaround
The following workaround solved the problem for me.

Add environment variables to docker-compose.yaml.
```
services:
  # Proxy for connecting between the browser and the Control Plane via gRPC.
  pipecd-gateway:
    image: envoyproxy/envoy-alpine:v1.18.3
    command:
      - -c /etc/envoy/envoy-config.yaml
    ports:
      - 9095:9095
      - 8080:9090
    volumes:
      - ./volume/envoy:/etc/envoy
      - ./volume/pipecd-secret:/etc/pipecd-secret
    # Add environment variable here
    environment:
      ENVOY_UID: 0
```

This workaround is based on this Issue.
https://github.com/envoyproxy/envoy/issues/11551
